### ISSUE TITLE
V10 配置公众号Token等报错

### ISSUE THREAD

**Issue by jaronemo** [JoneXiong/oejia_wx#11]
![image](https://cloud.githubusercontent.com/assets/8476734/21335001/5fe9a7a6-c696-11e6-930c-ebf127acb654.png)

**Comment by JoneXiong** [comment]
@jaronemo 这个是因为消息渠道id不对，你填上你渠道列表里对于的ID吧

**Comment by jaronemo** [comment]
所以不能用测试号？

**Comment by JoneXiong** [comment]
@jaronemo 不是， 跟那没关系 我们q聊吧
