### ISSUE TITLE
ParseError: "constraint 检查错误  字段`wxcorp_user_id`不存在

### ISSUE THREAD

**Issue by jili3221058** [JoneXiong/oejia_wx#14]
raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "constraint 检查错误
字段`wxcorp_user_id`不存在
错误的上下文:
视图 `res.partner.view.form.wx`
[view_id: 911, xml_id: n/a, model: res.partner, parent_id: 124]

**字段`wxcorp_user_id`不存在**

**Comment by jili3221058** [comment]
wx_inherit_ext.xml

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data>

        <record id="res_partner_wx_ext" model="ir.ui.view">
            <field name="name">res.partner.view.form.wx</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form" />
            <field name="arch" type="xml">
                <xpath expr="//field[@name='website']" position="after">
                    <field name="wxcorp_user_id"/> 
                </xpath>
            </field>
        </record>

    </data>
</openerp>

**Comment by jalins** [comment]
我也出现了这个问题，将<field name="wxcorp_user_id"/> 这行注释掉后又会出现另一个问题

**Comment by JoneXiong** [comment]
继承res.partner加了字段，请用命令 -u 的方式升级模块
