### ISSUE TITLE
在odoo11中安装失败

### ISSUE THREAD

**Issue by JacksonZheng** [JoneXiong/oejia_wx#20]
环境是centos7  rh-python35  ，点击安装时候报错
`错误:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 785, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/odoo/odoo11/odoo/tools/convert.py", line 832, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: 模块加载 oejia_wx 失败: 文件 oejia_wx/security/ir.model.access.csv 无法处理:
 在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (468, wx_user.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user_group'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (469, wx_user_group.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (470, wx_menu.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_base'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (471, wx_menu_item_base.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_left'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (472, wx_menu_item_left.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_middle'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (473, wx_menu_item_middle.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_right'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (474, wx_menu_item_right.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_corpuser'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (475, wx_corpuser.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_settings'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (476, wx_config_settings.group_wx_conf, t, null, 53, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_corpsettings'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (477, wx_config_corpsettings.group_wx_conf, t, null, 53, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_autoreply'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (478, wx_autoreply.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_articlesreply_article'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (479, wx_articlesreply_article.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_url'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (480, wx_action_act_url.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_text'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (481, wx_action_act_text.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_custom'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (482, wx_action_act_custom.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).

在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_article'
null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (483, wx_action_act_article.group_wx_op, t, null, 54, t, t, t, t, 1, 2018-07-25 08:22:50.122324, 1, 2018-07-25 08:22:50.122324).`

**Comment by JoneXiong** [comment]
这问题应该是由于加载了模块但是没有重启服务就直接安装导致的，请重启后再安装，另外11有点点更新， 请更新代码重启服务然后安装。我本地python3.5 已试 OK的
