### ISSUE TITLE
oauth.py代码错误

### ISSUE THREAD

**Issue by zhumeng459** [JoneXiong/oejia_wx#21]
文件：ext_libs\wechatpy\enterprise\client\api\oauth.py 第22行调用函数参数的代码有误：self.redirect_url 应直接改为：redirect_url ，类并无此属性。
　　第26行的： self.corp_id 应改为：self._client.corp_id 
　　第31行的：self.state 应改为 state 。

**Comment by JoneXiong** [comment]
项目已优化，wechatpy属于依赖库不再放到项目内部，pip install wechatpy 装新版试试，如有错可再提出来或直接向wechatpy 提 issue     @zhumeng459
