### ISSUE TITLE
odoo12 安装报错，model_id字段找不到

### ISSUE THREAD

**Issue by NewSNode** [JoneXiong/oejia_wx#27]
Odoo版本：Odoo 12.0-20190311 (社区版) 
部分报错信息如下：

Exception: 模块加载 oejia_wx 失败: 文件 oejia_wx\security/ir.model.access.csv 无法处理:
 在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_user_group'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_base'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_left'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_middle'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_menu_item_right'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_corpuser'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_settings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_corpsettings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_autoreply'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_articlesreply_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_url'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_text'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_custom'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_app_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_wxa'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_media'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_action_act_media'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_corpsettings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config_settings'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_app_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_articlesreply_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_media_article'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_send_mass'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_approval_record'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config'
在字段'Object'中没找到匹配的记录外部 ID 'model_wx_config'
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值
找不到字段 'Object' (model_id)所需的值

**Comment by JoneXiong** [comment]
明显的模型加载失败，检查下启动加载模块时的log，比如以来的库是否装好

**Comment by zoyoyo** [comment]
我也遇到一样的问题了，依赖的python库：wechatpy、pycrypto 都已装好。
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx# pip install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx# pip install wechatpy
Requirement already satisfied: wechatpy in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: xmltodict>=0.11.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: enum34>=1.1.4; python_version < "3.4" in /usr/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: optionaldict>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: six>=1.8.0 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: python-dateutil>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from wechatpy)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.3->wechatpy)
root@odoo:/usr/lib/python3/dist-packages/odoo/addons/oejia_wx#
还会有哪些问题呢？
