### ISSUE TITLE
微信模块使用问题

### ISSUE THREAD

**Issue by ZyfZyd** [JoneXiong/oejia_wx#32]
1.微信群发消息时报错
![image](https://user-images.githubusercontent.com/40428727/61921176-c5303b00-af8e-11e9-9b86-11f1a17ff925.png)
2.自动回复
（1）这块内容在Odoo中设置有数据，但是在微信公众平台没有显示
（2）关键词回复设置有内容，但是在公众号中无法触发
（3）公众号底部菜单，在Odoo中设置成功，公众号也生效，但是触发不了内容

**Comment by JoneXiong** [comment]
谢谢反馈，已修复，参考commit记录
