### ISSUE TITLE
Python library not installed: Crypto

### ISSUE THREAD

**Issue by kxu1988** [JoneXiong/oejia_wx#51]
odoo13安装时候报错
`Unable to install module "oejia_wx" because an external dependency is not met: Python library not installed: Crypto`

无论是在linux主机内还是在docker内都安装了依赖的python库：wechatpy、pycrypto、diskcache以及Crypto(均使用pip安装)

备注：我是用docker安装的odoo

**Comment by JoneXiong** [comment]
1. 请确认安装到了跑odoo的python里
2. 安装库后最好重启下odoo服务再安装模块

**Comment by filwu8** [comment]
> docker 用的python3，这样安装：我已经装好了，但是还是抱错，已经起了个新的issues

pip3 install pycryptodome

pip3 install crypto

pip3 install pycrypto

pip3 install wechatpy

pip3 install diskcache
