### ISSUE TITLE
运行安装时会报 warning的log,小细节改进

### ISSUE THREAD

**Issue by guohuadeng** [JoneXiong/oejia_wx#52]
1. 有些模型没有_description 
比如 `_name = 'wx.menu.item.base'`
会在运行时报 log问题， 看能加上最好

2. 字段同名，也会报 log警告，wx_media
`
    update_time = fields.Char('更新时间')
    update_time_show = fields.Char('更新时间',compute='_update_time_show')`

**Comment by JoneXiong** [comment]
感谢反馈，已处理
